import { ImageSourcePropType } from "react-native";

interface Icons {
  myMentors: ImageSourcePropType;
  Revitalization: ImageSourcePropType;
  Assessments: ImageSourcePropType;
  progress: ImageSourcePropType;
  Appointments: ImageSourcePropType;
  profile: ImageSourcePropType;
  myProfile: ImageSourcePropType;
  document: ImageSourcePropType;
  assignment: ImageSourcePropType;
  certificate: ImageSourcePropType;
  microGrant: ImageSourcePropType;
  settings: ImageSourcePropType;
  changePass: ImageSourcePropType;
  turnOffNotification: ImageSourcePropType;
  changeMentor: ImageSourcePropType;
  logout: ImageSourcePropType;
  logo: ImageSourcePropType;
  notification: ImageSourcePropType;
  backgroundImage: ImageSourcePropType;
  phone: ImageSourcePropType;
  message: ImageSourcePropType;
  mail: ImageSourcePropType;
  whatsapp: ImageSourcePropType;
  forward: ImageSourcePropType;
  duoMeet: ImageSourcePropType;
  googleMeet: ImageSourcePropType;
  menuVertical: ImageSourcePropType;
  Revitalization2: ImageSourcePropType;
  Assessments2: ImageSourcePropType;
  progress2: ImageSourcePropType;
  Appointments2: ImageSourcePropType;
  attachment: ImageSourcePropType;
  edit: ImageSourcePropType;
  video: ImageSourcePropType;
  search: ImageSourcePropType;
  edit2: ImageSourcePropType;
  profile2: ImageSourcePropType;
  list: ImageSourcePropType;
  grid: ImageSourcePropType;
  dummyUser: ImageSourcePropType;
  dummyUser2: ImageSourcePropType;
  dummyImage: ImageSourcePropType;
  detailedRoadmapImage: ImageSourcePropType;
  download: ImageSourcePropType;
  gradientDownload: ImageSourcePropType;
  delete: ImageSourcePropType;
  upload: ImageSourcePropType;
  close: ImageSourcePropType;
  addIcon: ImageSourcePropType;
  location: ImageSourcePropType;
  deleteIcon: ImageSourcePropType;
  certificateImage: ImageSourcePropType;
  plusIcon: ImageSourcePropType;
  universityIcon: ImageSourcePropType;
  loadingIcon: ImageSourcePropType;
  communityImage: ImageSourcePropType;
  profileUpload: ImageSourcePropType;
  gradientClip: ImageSourcePropType;
  gradientUpload: ImageSourcePropType;
  church2: ImageSourcePropType;
  church1: ImageSourcePropType;
  player: ImageSourcePropType;
  playButton: ImageSourcePropType;
  prevPlayer: ImageSourcePropType;
  nextPlayer: ImageSourcePropType;
  loader: ImageSourcePropType;
  media2: ImageSourcePropType;
  videoMedia: ImageSourcePropType
  attachPin: ImageSourcePropType;
  certificateBadge: ImageSourcePropType;
  documentsIcon: ImageSourcePropType;
  fieldMentorIcon: ImageSourcePropType;
  calendarIcon: ImageSourcePropType;
  changeModeIcon: ImageSourcePropType;
  rescheduleIcon: ImageSourcePropType;
  profileTabIcon: ImageSourcePropType;
  homeTabIcon: ImageSourcePropType;
  schedule: ImageSourcePropType;
  assignmentIcon: ImageSourcePropType;
}

export const icons: Icons = {
  myMentors: require("@/assets/icons/myMentors.png"),
  Revitalization: require("@/assets/icons/revitalizationRoadmap.png"),
  Assessments: require("@/assets/icons/assessments.png"),
  progress: require("@/assets/icons/Positive Dynamic.png"),
  Appointments: require("@/assets/icons/People.png"),
  profile: require("@/assets/icons/Profile.png"),
  myProfile: require("@/assets/icons/JOHN ROSS PROF PIC.png"),
  document: require("@/assets/icons/Documents.png"),
  assignment: require("@/assets/icons/assignments.png"),
  certificate: require("@/assets/icons/Certificate.png"),
  microGrant: require("@/assets/icons/MicroGrant.png"),
  settings: require("@/assets/icons/Settings.png"),
  changePass: require("@/assets/icons/changePassword.png"),
  turnOffNotification: require("@/assets/icons/turnOffNotification.png"),
  changeMentor: require("@/assets/icons/changeMentor.png"),
  logout: require("@/assets/icons/Logout.png"),
  logo: require("@/assets/logos/CCClogo.png"),
  notification: require("@/assets/icons/Notification.png"),
  backgroundImage: require("@/assets/icons/homeScreenBG.png"),
  phone: require("@/assets/icons/Phone.png"),
  message: require("@/assets/icons/message.png"),
  mail: require("@/assets/icons/Envelope.png"),
  whatsapp: require("@/assets/icons/WhatsApp.png"),
  forward: require("@/assets/icons/Forward.png"),
  duoMeet: require("@/assets/icons/ZOOM  CALL ICON.png"),
  googleMeet: require("@/assets/icons/GOOGLEMEET CALL ICON.png"),
  menuVertical: require("@/assets/icons/Menu Vertical.png"),
  Revitalization2: require("@/assets/icons/revitalization2.png"),
  Assessments2: require("@/assets/icons/assessment2.png"),
  progress2: require("@/assets/icons/progress2.png"),
  Appointments2: require("@/assets/icons/appointments2.png"),
  attachment: require("@/assets/icons/attachment.png"),
  edit: require("@/assets/icons/edit.png"),
  video: require("@/assets/icons/VIDEO.png"),
  search: require("@/assets/icons/search.png"),
  edit2: require("@/assets/icons/edit2.png"),
  profile2: require("@/assets/icons/Profile2.png"),
  list: require("@/assets/icons/List.png"),
  grid: require("@/assets/icons/Grid.png"),
  dummyUser: require("@/assets/icons/user.png"),
  dummyUser2: require("@/assets/icons/user1.png"),
  dummyImage: require("@/assets/icons/reviltalizationDummyImage.jpeg"),
  detailedRoadmapImage: require("@/assets/icons/detailedRoadMapDummy.jpg"),
  download: require("@/assets/icons/Download.png"),
  gradientDownload: require("@/assets/icons/gradientDownload.png"),
  delete: require("@/assets/icons/Delete.png"),
  upload: require("@/assets/icons/upload.png"),
  close: require("@/assets/icons/Close.png"),
  addIcon: require("@/assets/icons/Add New.png"),
  location: require("@/assets/icons/Location.png"),
  deleteIcon: require("@/assets/icons/DeleteIcon.png"),
  certificateImage: require("@/assets/icons/certificateImage.png"),
  plusIcon: require("@/assets/icons/plus-icon.png"),
  universityIcon: require("@/assets/images/university.png"),
  loadingIcon: require("@/assets/images/loading.png"),
  communityImage: require("@/assets/images/community.png"),
  profileUpload: require("@/assets/images/Profile.png"),
  gradientClip: require("@/assets/images/gradient-clip.png"),
  gradientUpload: require("@/assets/images/gradient-upload.png"),
  church2: require("@/assets/images/church-2.png"),
  church1: require("@/assets/images/church-1.png"),
  player: require("@/assets/images/player.png"),
  playButton: require("@/assets/images/play-button.png"),
  prevPlayer: require("@/assets/images/prev-player.png"),
  nextPlayer: require("@/assets/images/next-player.png"),
  loader: require("@/assets/images/loader.png"),
  media2: require("@/assets/images/media-2.png"),
  videoMedia: require("@/assets/images/VIDEO.png"),
  attachPin: require("@/assets/images/attach-pin.png"),
  certificateBadge: require("@/assets/icons/certificate-badge.png"),
  documentsIcon: require("@/assets/icons/documents-icon.png"),
  fieldMentorIcon: require("@/assets/icons/field-mentor-icon.png"),
  calendarIcon: require("@/assets/icons/calendar.png"),
  changeModeIcon: require("@/assets/icons/change_mode.png"),
  rescheduleIcon: require("@/assets/icons/reschedule.png"),
  profileTabIcon: require("@/assets/icons/profile-tab.png"),
  homeTabIcon: require("@/assets/icons/home-tab.png"),
  schedule: require("@/assets/icons/schedule.png"),
  assignmentIcon: require("@/assets/icons/assignment.png"),
};
