import { ChecklistSchema, FormSchema, MeetingSchema, RevitalizationData, SignSchema, UploadSchema } from "./types";

// export const mockRevitalization: RevitalizationData = {
//     program: {
//         id: 'revitalization',
//         title: 'Revitalization Roadmap',
//         phases: ['jump-start', 'phase-1', 'phase-2', 'phase-3'],
//     },
//     phases: {
//         'jump-start': {
//             id: 'jump-start',
//             code: 'JUMP_START',
//             title: 'Jump–start',
//             subtitle: 'Attend a two–day revitalization jump–start session',
//             estMonthsMin: 1,
//             estMonthsMax: 2,
//             coverImage: 'https://example.com/jump.jpg',
//             items: ['jump-start-session'], // single item, not multiple
//         },
//         'phase-1': {
//             id: 'phase-1',
//             code: 'PHASE_1',
//             title: 'Self Revitalization Phase',
//             subtitle: 'Conflict resolution and theory of change',
//             estMonthsMin: 1,
//             estMonthsMax: 2,
//             coverImage: 'https://example.com/p1.jpg',
//             items: [
//                 'p1-sign-covenant',
//                 'p1-upload-strategy',
//                 'p1-mentor-meeting',
//                 'p1-complete-assessment',
//                 'p1-train-leadership',
//                 'p1-submit-budget',
//                 'p1-share-testimony',
//                 'p1-checklist-evangelism',
//             ],
//         },
//         'phase-2': {
//             id: 'phase-2',
//             code: 'PHASE_2',
//             title: 'Church Empowerment Phase',
//             subtitle: 'Community programs and long-term impact',
//             estMonthsMin: 3,
//             estMonthsMax: 9,
//             coverImage: 'https://example.com/p2.jpg',
//             items: [
//                 'p2-mou-with-ngos',
//                 'p2-upload-calendar',
//                 'p2-community-survey',
//                 'p2-run-pilot-program',
//                 'p2-upload-report',
//             ],
//         },
//         'phase-3': {
//             id: 'phase-3',
//             code: 'PHASE_3',
//             title: 'Community Revitalization and Multiplication',
//             subtitle: 'Review outcomes and empower others',
//             estMonthsMin: 10,
//             estMonthsMax: 12,
//             coverImage: 'https://example.com/p3.jpg',
//             items: [
//                 'p3-train-new-coaches',
//                 'p3-plant-microgroups',
//                 'p3-measure-kpis',
//                 'p3-graduation',
//             ],
//         },
//     },
//     items: {
//         // Jump-start child roadmaps
//         'jump-start-session': {
//             id: 'jump-start-session',
//             phaseId: 'jump-start',
//             kind: 'CHILD_ROADMAP',
//             title: 'Jump–start',
//             description: 'Attend a two–day revitalization jump–start session',
//             status: 'NOT_STARTED',
//             sessionDate: '2024-10-11',
//             steps: [
//                 { id: 's1', title: 'Christ Method Alone (Why & How)', done: false },
//                 { id: 's2', title: 'Self-Leadership', done: false },
//                 { id: 's3', title: 'Dealing with Resistance', done: false },
//                 { id: 's4', title: 'Empower Others-Spiritual Renewal', done: false },
//                 { id: 's5', title: 'Community Engagement - Need Assessments', done: false },
//                 { id: 's6', title: 'Cycle of Evangelism & Discipleship', done: false },
//             ],
//             meta: { hasOverviewTab: true },
//         },

//         // Phase 1 tasks (heterogeneous)
//         'p1-sign-roadmap': {
//             id: 'p1-sign-roadmap',
//             phaseId: 'phase-1',
//             kind: 'TASK',
//             title: '12-Month Mentoring Revitalization Roadmap Approval',
//             description: '12-Month Revitalization Roadmap for pastoral mentoring and church revitalization growth',
//             status: 'NOT_STARTED',
//             taskType: 'SIGN',
//             schema: {
//                 agreementText: 'I agree to participate in the 12-month revitalization mentoring and church growth roadmap provided by The Center for Community Change',
//                 requireCheckbox: true,
//                 signatureLabel: 'Signature Required here',
//                 documentUrl: 'https://example.com/12-month-roadmap.pdf',
//             } as SignSchema,
//             meta: {
//                 coverImage: 'https://example.com/sign.jpg',
//                 completionTimeMonths: '1 - 2',
//                 roadmapText: 'Sign 12-Month Revitalization Roadmap',
//                 viewTimelineUrl: '/timeline/12-month-mentoring',
//             },
//         },

//         'p1-prayer-strategy': {
//             id: 'p1-prayer-strategy',
//             phaseId: 'phase-1',
//             kind: 'TASK',
//             title: 'Prayer and Visitation Strategy',
//             description: 'Develop a prayer and visitation strategy and upload document',
//             status: 'NOT_STARTED',
//             taskType: 'UPLOAD',
//             schema: {
//                 accept: ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
//                 maxSizeMB: 10,
//                 maxFiles: 1,
//                 label: 'Upload Strategy',
//                 description: 'Upload your prayer and visitation strategy document',
//             } as UploadSchema,
//             meta: {
//                 coverImage: 'https://example.com/prayer.jpg',
//                 completionTimeMonths: '1 - 2',
//                 roadmapText: 'Create a prayer and visitation strategy',
//             },
//         },

//         'p1-pastoral-profile': {
//             id: 'p1-pastoral-profile',
//             phaseId: 'phase-1',
//             kind: 'TASK',
//             title: 'Pastoral Ministry Profile (PMP)',
//             description: 'Complete a personal pastoral assessment taking a deeper look into your ministry',
//             status: 'NOT_STARTED',
//             taskType: 'FORM',
//             schema: {
//                 fields: [
//                     { id: 'leadership_style', type: 'dropdown', label: 'Leadership Style', required: true, options: ['Visionary', 'Servant', 'Democratic', 'Transformational'] },
//                     { id: 'ministry_focus', type: 'multi-select', label: 'Ministry Focus Areas', options: ['Youth', 'Outreach', 'Discipleship', 'Worship', 'Administration'] },
//                     { id: 'challenges', type: 'textarea', label: 'Current Ministry Challenges', required: true, placeholder: 'Describe your challenges...' },
//                     { id: 'years_ministry', type: 'number', label: 'Years in Ministry', validation: { min: 0, max: 60 } },
//                 ],
//                 submitLabel: 'Take PMP Survey',
//             } as FormSchema,
//             meta: {
//                 coverImage: 'https://example.com/pmp.jpg',
//                 completionTimeMonths: '1 - 2',
//                 roadmapText: 'Complete a Pastoral Ministry Profile (PMP)',
//             },
//         },

//         'p1-gods-vision': {
//             id: 'p1-gods-vision',
//             phaseId: 'phase-1',
//             kind: 'TASK',
//             title: "God's Vision for your Church",
//             description: 'View do you see your church as a Christ formed place and develop',
//             status: 'NOT_STARTED',
//             taskType: 'UPLOAD',
//             schema: {
//                 accept: ['application/pdf', 'image/*', 'video/*'],
//                 maxSizeMB: 50,
//                 maxFiles: 3,
//                 label: 'Upload Vision Document',
//                 description: 'Upload your vision document, images, or video',
//             } as UploadSchema,
//             meta: {
//                 coverImage: 'https://example.com/vision.jpg',
//                 completionTimeMonths: '1 - 2',
//                 roadmapText: 'Create a Vision for your church',
//             },
//         },

//         'p1-calendar': {
//             id: 'p1-calendar',
//             phaseId: 'phase-1',
//             kind: 'TASK',
//             title: 'Calendar',
//             description: 'Create a calendar that will complement your vision for the church',
//             status: 'NOT_STARTED',
//             taskType: 'UPLOAD',
//             schema: {
//                 accept: ['application/pdf', 'text/calendar', 'application/vnd.ms-excel', 'text/csv'],
//                 maxSizeMB: 5,
//                 maxFiles: 1,
//                 label: 'Upload Calendar',
//                 description: 'Upload your church calendar',
//             } as UploadSchema,
//             meta: {
//                 coverImage: 'https://example.com/calendar.jpg',
//                 completionTimeMonths: '1 - 2',
//                 roadmapText: 'Create your Vision Plan (create a calendar)',
//             },
//         },

//         'p1-mentor-disciple': {
//             id: 'p1-mentor-disciple',
//             phaseId: 'phase-1',
//             kind: 'TASK',
//             title: 'Identify a Mentor/Disciple',
//             description: 'Identify a Mentor/Disciple and submit their name and contact information to advance service platform',
//             status: 'NOT_STARTED',
//             taskType: 'FORM',
//             schema: {
//                 fields: [
//                     { id: 'name', type: 'text', label: 'Name of Mentor/Disciple', required: true },
//                     { id: 'email', type: 'email', label: 'Email', required: true },
//                     { id: 'phone', type: 'text', label: 'Phone Number', required: true },
//                     { id: 'role', type: 'dropdown', label: 'Role', options: ['Mentor', 'Disciple'], required: true },
//                 ],
//                 submitLabel: 'Submit',
//             } as FormSchema,
//             meta: {
//                 coverImage: 'https://example.com/mentor.jpg',
//                 completionTimeMonths: '1 - 2',
//                 roadmapText: 'Identify a Mentor/Disciple and submit contact',
//             },
//         },

//         'p1-community-engagement': {
//             id: 'p1-community-engagement',
//             phaseId: 'phase-1',
//             kind: 'TASK',
//             title: 'Community Engagement Project',
//             description: 'Choose a community engagement project that aligns with your church and upload.',
//             status: 'NOT_STARTED',
//             taskType: 'FORM',
//             schema: {
//                 fields: [
//                     { id: 'project_name', type: 'text', label: 'Community Engagement Project', required: true },
//                     { id: 'project_file', type: 'text', label: 'Upload your Community Engagement Project', placeholder: 'File upload (handled separately)' },
//                     { id: 'follow_up_event1', type: 'text', label: 'Follow up Event 1', placeholder: 'TO ADD IT' },
//                     { id: 'follow_up_event1_date', type: 'date', label: 'Choose your Follow up Event 1', required: true },
//                     { id: 'follow_up_event2', type: 'text', label: 'Follow up Event 2', placeholder: 'TO ADD IT' },
//                     { id: 'follow_up_event2_date', type: 'date', label: 'Choose your Follow up Event 2', required: true },
//                 ],
//                 submitLabel: 'Submit',
//             } as FormSchema,
//             meta: {
//                 coverImage: 'https://example.com/community.jpg',
//                 completionTimeMonths: '1 - 2',
//                 roadmapText: 'Choose a community engagement project',
//                 hasFileUpload: true,
//             },
//         },
//         // Phase 2 sample tasks
//         'p2-mou-with-ngos': {
//             id: 'p2-mou-with-ngos',
//             phaseId: 'phase-2',
//             kind: 'TASK',
//             title: 'Sign MoU with NGOs',
//             description: 'Execute partnership MoU',
//             status: 'NOT_STARTED',
//             taskType: 'SIGN',
//             schema: { docUrl: 'https://example.com/mou.pdf' },
//         },
//         'p2-upload-calendar': {
//             id: 'p2-upload-calendar',
//             phaseId: 'phase-2',
//             kind: 'TASK',
//             title: 'Upload Outreach Calendar',
//             description: 'Provide 6‑month program calendar',
//             status: 'NOT_STARTED',
//             taskType: 'UPLOAD',
//             schema: { accept: ['application/pdf'] },
//         },
//         'p2-community-survey': {
//             id: 'p2-community-survey',
//             phaseId: 'phase-2',
//             kind: 'TASK',
//             title: 'Community Survey',
//             description: 'Submit 100+ survey responses',
//             status: 'NOT_STARTED',
//             taskType: 'FORM',
//             schema: { fields: [{ id: 'f1', type: 'number', label: 'Responses' }] },
//         },
//         'p2-run-pilot-program': {
//             id: 'p2-run-pilot-program',
//             phaseId: 'phase-2',
//             kind: 'TASK',
//             title: 'Run Pilot Program',
//             description: 'Complete a 4‑week pilot and log attendance',
//             status: 'NOT_STARTED',
//             taskType: 'CHECKLIST',
//             checklist: [
//                 { id: 'w1', text: 'Week 1 complete', done: false },
//                 { id: 'w2', text: 'Week 2 complete', done: false },
//                 { id: 'w3', text: 'Week 3 complete', done: false },
//                 { id: 'w4', text: 'Week 4 complete', done: false },
//             ],
//         },
//         'p2-upload-report': {
//             id: 'p2-upload-report',
//             phaseId: 'phase-2',
//             kind: 'TASK',
//             title: 'Upload Pilot Report',
//             description: 'Submit PDF with outcomes and photos',
//             status: 'NOT_STARTED',
//             taskType: 'UPLOAD',
//             schema: { accept: ['application/pdf'] },
//         },

//         // Phase 3 sample tasks
//         'p3-train-new-coaches': {
//             id: 'p3-train-new-coaches',
//             phaseId: 'phase-3',
//             kind: 'TASK',
//             title: 'Train New Coaches',
//             description: 'Run a coach training weekend',
//             status: 'NOT_STARTED',
//             taskType: 'CHECKLIST',
//             checklist: [
//                 { id: 't1', text: 'Curriculum prepared', done: false },
//                 { id: 't2', text: '15 attendees confirmed', done: false },
//             ],
//         },
//         'p3-plant-microgroups': {
//             id: 'p3-plant-microgroups',
//             phaseId: 'phase-3',
//             kind: 'TASK',
//             title: 'Plant Micro‑groups',
//             description: 'Launch 5 micro‑groups',
//             status: 'NOT_STARTED',
//             taskType: 'FORM',
//             schema: [
//                 { id: 'g1', type: 'number', label: 'Groups started' },
//                 { id: 'g2', type: 'textarea', label: 'Locations' },
//             ],
//         },
//         'p3-measure-kpis': {
//             id: 'p3-measure-kpis',
//             phaseId: 'phase-3',
//             kind: 'TASK',
//             title: 'Measure KPIs',
//             description: 'Submit quarterly metrics',
//             status: 'NOT_STARTED',
//             taskType: 'UPLOAD',
//             schema: { accept: ['text/csv', 'application/vnd.ms-excel'] },
//         },
//         'p3-graduation': {
//             id: 'p3-graduation',
//             phaseId: 'phase-3',
//             kind: 'TASK',
//             title: 'Graduation',
//             description: 'Final review and certificate issue',
//             status: 'NOT_STARTED',
//             taskType: 'MEETING',
//             schema: { durationMin: 60 },
//         },
//     },
// };


export const mockRevitalization: RevitalizationData = {
    program: {
        id: 'revitalization',
        title: 'Revitalization Roadmap',
        phases: ['jump-start', 'phase-1', 'phase-2', 'phase-3'],
    },
    phases: {
        'jump-start': {
            id: 'jump-start',
            code: 'JUMP_START',
            title: 'Jump–start',
            subtitle: 'Attend a two–day revitalization jump–start session',
            estMonthsMin: 1,
            estMonthsMax: 2,
            coverImage: 'https://example.com/jump.jpg',
            items: ['jump-start-session'],
        },
        'phase-1': {
            id: 'phase-1',
            code: 'PHASE_1',
            title: 'Self Revitalization Phase',
            subtitle: 'Conflict resolution and theory of change',
            estMonthsMin: 1,
            estMonthsMax: 2,
            coverImage: 'https://example.com/p1.jpg',
            items: [
                'p1-sign-roadmap',           // ✅ was 'p1-sign-covenant'
                'p1-prayer-strategy',        // ✅ was 'p1-upload-strategy'
                'p1-mentor-disciple',        // ✅ was 'p1-mentor-meeting'
                'p1-pastoral-profile',       // ✅ was 'p1-complete-assessment'
                'p1-gods-vision',            // ✅ was 'p1-train-leadership'
                'p1-calendar',               // ✅ was 'p1-submit-budget'
                'p1-community-engagement',   // ✅ was 'p1-share-testimony'
                // Add one more if needed, or remove extra
                // 'p1-checklist-evangelism' ← doesn't exist, so omit
            ],
        },
        'phase-2': {
            id: 'phase-2',
            code: 'PHASE_2',
            title: 'Church Empowerment Phase',
            subtitle: 'Community programs and long-term impact',
            estMonthsMin: 3,
            estMonthsMax: 9,
            coverImage: 'https://example.com/p2.jpg',
            items: [
                'p2-mou-with-ngos',
                'p2-upload-calendar',
                'p2-community-survey',
                'p2-run-pilot-program',
                'p2-upload-report',
            ],
        },
        'phase-3': {
            id: 'phase-3',
            code: 'PHASE_3',
            title: 'Community Revitalization and Multiplication',
            subtitle: 'Review outcomes and empower others',
            estMonthsMin: 10,
            estMonthsMax: 12,
            coverImage: 'https://example.com/p3.jpg',
            items: [
                'p3-train-new-coaches',
                'p3-plant-microgroups',
                'p3-measure-kpis',
                'p3-graduation',
            ],
        },
    },
    items: {
        // Jump-start
        'jump-start-session': {
            id: 'jump-start-session',
            phaseId: 'jump-start',
            kind: 'CHILD_ROADMAP',
            title: 'Jump–start',
            description: 'Attend a two–day revitalization jump–start session',
            status: 'NOT_STARTED',
            sessionDate: '2024-10-11',
            steps: [
                { id: 's1', title: 'Christ Method Alone (Why & How)', done: false },
                { id: 's2', title: 'Self-Leadership', done: false },
                { id: 's3', title: 'Dealing with Resistance', done: false },
                { id: 's4', title: 'Empower Others-Spiritual Renewal', done: false },
                { id: 's5', title: 'Community Engagement - Need Assessments', done: false },
                { id: 's6', title: 'Cycle of Evangelism & Discipleship', done: false },
            ],
            meta: { hasOverviewTab: true },
        },

        // Phase 1 tasks
        'p1-sign-roadmap': {
            id: 'p1-sign-roadmap',
            phaseId: 'phase-1',
            kind: 'TASK',
            title: '12-Month Mentoring Revitalization Roadmap Approval',
            description: '12-Month Revitalization Roadmap for pastoral mentoring and church revitalization growth',
            status: 'NOT_STARTED',
            taskType: 'SIGN',
            schema: {
                agreementText: 'I agree to participate in the 12-month revitalization mentoring and church growth roadmap provided by The Center for Community Change',
                requireCheckbox: true,
                signatureLabel: 'Signature Required here',
                documentUrl: 'https://example.com/12-month-roadmap.pdf',
            } satisfies SignSchema,
            meta: {
                coverImage: 'https://example.com/sign.jpg',
                completionTimeMonths: '1 - 2',
                roadmapText: 'Sign 12-Month Revitalization Roadmap',
                viewTimelineUrl: '/timeline/12-month-mentoring',
            },
        },

        'p1-prayer-strategy': {
            id: 'p1-prayer-strategy',
            phaseId: 'phase-1',
            kind: 'TASK',
            title: 'Prayer and Visitation Strategy',
            description: 'Develop a prayer and visitation strategy and upload document',
            status: 'NOT_STARTED',
            taskType: 'UPLOAD',
            schema: {
                accept: ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
                maxSizeMB: 10,
                maxFiles: 1,
                label: 'Upload Strategy',
                description: 'Upload your prayer and visitation strategy document',
            } satisfies UploadSchema,
            meta: {
                coverImage: 'https://example.com/prayer.jpg',
                completionTimeMonths: '1 - 2',
                roadmapText: 'Create a prayer and visitation strategy',
            },
        },

        'p1-pastoral-profile': {
            id: 'p1-pastoral-profile',
            phaseId: 'phase-1',
            kind: 'TASK',
            title: 'Pastoral Ministry Profile (PMP)',
            description: 'Complete a personal pastoral assessment taking a deeper look into your ministry',
            status: 'NOT_STARTED',
            taskType: 'FORM',
            schema: {
                fields: [
                    { id: 'leadership_style', type: 'dropdown', label: 'Leadership Style', required: true, options: ['Visionary', 'Servant', 'Democratic', 'Transformational'] },
                    { id: 'ministry_focus', type: 'multi-select', label: 'Ministry Focus Areas', options: ['Youth', 'Outreach', 'Discipleship', 'Worship', 'Administration'] },
                    { id: 'challenges', type: 'textarea', label: 'Current Ministry Challenges', required: true, placeholder: 'Describe your challenges...' },
                    { id: 'years_ministry', type: 'number', label: 'Years in Ministry', validation: { min: 0, max: 60 } },
                ],
                submitLabel: 'Take PMP Survey',
            } satisfies FormSchema,
            meta: {
                coverImage: 'https://example.com/pmp.jpg',
                completionTimeMonths: '1 - 2',
                roadmapText: 'Complete a Pastoral Ministry Profile (PMP)',
            },
        },

        'p1-gods-vision': {
            id: 'p1-gods-vision',
            phaseId: 'phase-1',
            kind: 'TASK',
            title: "God's Vision for your Church",
            description: 'View do you see your church as a Christ formed place and develop',
            status: 'NOT_STARTED',
            taskType: 'UPLOAD',
            schema: {
                accept: ['application/pdf', 'image/*', 'video/*'],
                maxSizeMB: 50,
                maxFiles: 3,
                label: 'Upload Vision Document',
                description: 'Upload your vision document, images, or video',
            } satisfies UploadSchema,
            meta: {
                coverImage: 'https://example.com/vision.jpg',
                completionTimeMonths: '1 - 2',
                roadmapText: 'Create a Vision for your church',
            },
        },

        'p1-calendar': {
            id: 'p1-calendar',
            phaseId: 'phase-1',
            kind: 'TASK',
            title: 'Calendar',
            description: 'Create a calendar that will complement your vision for the church',
            status: 'NOT_STARTED',
            taskType: 'UPLOAD',
            schema: {
                accept: ['application/pdf', 'text/calendar', 'application/vnd.ms-excel', 'text/csv'],
                maxSizeMB: 5,
                maxFiles: 1,
                label: 'Upload Calendar',
                description: 'Upload your church calendar',
            } satisfies UploadSchema,
            meta: {
                coverImage: 'https://example.com/calendar.jpg',
                completionTimeMonths: '1 - 2',
                roadmapText: 'Create your Vision Plan (create a calendar)',
            },
        },

        'p1-mentor-disciple': {
            id: 'p1-mentor-disciple',
            phaseId: 'phase-1',
            kind: 'TASK',
            title: 'Identify a Mentor/Disciple',
            description: 'Identify a Mentor/Disciple and submit their name and contact information to advance service platform',
            status: 'NOT_STARTED',
            taskType: 'FORM',
            schema: {
                fields: [
                    { id: 'name', type: 'text', label: 'Name of Mentor/Disciple', required: true },
                    { id: 'email', type: 'email', label: 'Email', required: true },
                    { id: 'phone', type: 'text', label: 'Phone Number', required: true },
                    { id: 'role', type: 'dropdown', label: 'Role', options: ['Mentor', 'Disciple'], required: true },
                ],
                submitLabel: 'Submit',
            } satisfies FormSchema,
            meta: {
                coverImage: 'https://example.com/mentor.jpg',
                completionTimeMonths: '1 - 2',
                roadmapText: 'Identify a Mentor/Disciple and submit contact',
            },
        },

        'p1-community-engagement': {
            id: 'p1-community-engagement',
            phaseId: 'phase-1',
            kind: 'TASK',
            title: 'Community Engagement Project',
            description: 'Choose a community engagement project that aligns with your church and upload.',
            status: 'NOT_STARTED',
            taskType: 'FORM',
            schema: {
                fields: [
                    { id: 'project_name', type: 'text', label: 'Community Engagement Project', required: true },
                    { id: 'project_file', type: 'text', label: 'Upload your Community Engagement Project', placeholder: 'File upload (handled separately)' },
                    { id: 'follow_up_event1', type: 'text', label: 'Follow up Event 1', placeholder: 'TO ADD IT' },
                    { id: 'follow_up_event1_date', type: 'date', label: 'Choose your Follow up Event 1', required: true },
                    { id: 'follow_up_event2', type: 'text', label: 'Follow up Event 2', placeholder: 'TO ADD IT' },
                    { id: 'follow_up_event2_date', type: 'date', label: 'Choose your Follow up Event 2', required: true },
                ],
                submitLabel: 'Submit',
            } satisfies FormSchema,
            meta: {
                coverImage: 'https://example.com/community.jpg',
                completionTimeMonths: '1 - 2',
                roadmapText: 'Choose a community engagement project',
                hasFileUpload: true,
            },
        },

        // Phase 2
        'p2-mou-with-ngos': {
            id: 'p2-mou-with-ngos',
            phaseId: 'phase-2',
            kind: 'TASK',
            title: 'Sign MoU with NGOs',
            description: 'Execute partnership MoU',
            status: 'NOT_STARTED',
            taskType: 'SIGN',
            schema: {
                agreementText: 'I agree to the MoU terms.',
                requireCheckbox: true,
                documentUrl: 'https://example.com/mou.pdf',
            } satisfies SignSchema,
        },
        'p2-upload-calendar': {
            id: 'p2-upload-calendar',
            phaseId: 'phase-2',
            kind: 'TASK',
            title: 'Upload Outreach Calendar',
            description: 'Provide 6‑month program calendar',
            status: 'NOT_STARTED',
            taskType: 'UPLOAD',
            schema: {
                accept: ['application/pdf'],
                maxSizeMB: 5,
                maxFiles: 1,
                label: 'Upload Calendar',
            } satisfies UploadSchema,
        },
        'p2-community-survey': {
            id: 'p2-community-survey',
            phaseId: 'phase-2',
            kind: 'TASK',
            title: 'Community Survey',
            description: 'Submit 100+ survey responses',
            status: 'NOT_STARTED',
            taskType: 'FORM',
            schema: {
                fields: [{ id: 'responses', type: 'number', label: 'Number of Responses', required: true }],
                submitLabel: 'Submit Survey Data',
            } satisfies FormSchema,
        },
        'p2-run-pilot-program': {
            id: 'p2-run-pilot-program',
            phaseId: 'phase-2',
            kind: 'TASK',
            title: 'Run Pilot Program',
            description: 'Complete a 4‑week pilot and log attendance',
            status: 'NOT_STARTED',
            taskType: 'CHECKLIST',
            schema: {
                items: [
                    { id: 'w1', text: 'Week 1 complete', done: false },
                    { id: 'w2', text: 'Week 2 complete', done: false },
                    { id: 'w3', text: 'Week 3 complete', done: false },
                    { id: 'w4', text: 'Week 4 complete', done: false },
                ],
            } satisfies ChecklistSchema,
        },
        'p2-upload-report': {
            id: 'p2-upload-report',
            phaseId: 'phase-2',
            kind: 'TASK',
            title: 'Upload Pilot Report',
            description: 'Submit PDF with outcomes and photos',
            status: 'NOT_STARTED',
            taskType: 'UPLOAD',
            schema: {
                accept: ['application/pdf'],
                maxSizeMB: 20,
                maxFiles: 1,
                label: 'Upload Report',
            } satisfies UploadSchema,
        },

        // Phase 3
        'p3-train-new-coaches': {
            id: 'p3-train-new-coaches',
            phaseId: 'phase-3',
            kind: 'TASK',
            title: 'Train New Coaches',
            description: 'Run a coach training weekend',
            status: 'NOT_STARTED',
            taskType: 'CHECKLIST',
            schema: {
                items: [
                    { id: 't1', text: 'Curriculum prepared', done: false },
                    { id: 't2', text: '15 attendees confirmed', done: false },
                ],
            } satisfies ChecklistSchema,
        },
        'p3-plant-microgroups': {
            id: 'p3-plant-microgroups',
            phaseId: 'phase-3',
            kind: 'TASK',
            title: 'Plant Micro‑groups',
            description: 'Launch 5 micro‑groups',
            status: 'NOT_STARTED',
            taskType: 'FORM',
            schema: {
                fields: [
                    { id: 'groups_started', type: 'number', label: 'Number of Groups Started', required: true },
                    { id: 'locations', type: 'textarea', label: 'Locations', required: true },
                ],
                submitLabel: 'Submit',
            } satisfies FormSchema,
        },
        'p3-measure-kpis': {
            id: 'p3-measure-kpis',
            phaseId: 'phase-3',
            kind: 'TASK',
            title: 'Measure KPIs',
            description: 'Submit quarterly metrics',
            status: 'NOT_STARTED',
            taskType: 'UPLOAD',
            schema: {
                accept: ['text/csv', 'application/vnd.ms-excel'],
                maxSizeMB: 10,
                maxFiles: 1,
                label: 'Upload KPI Report',
            } satisfies UploadSchema,
        },
        'p3-graduation': {
            id: 'p3-graduation',
            phaseId: 'phase-3',
            kind: 'TASK',
            title: 'Graduation',
            description: 'Final review and certificate issue',
            status: 'NOT_STARTED',
            taskType: 'MEETING',
            schema: {
                durationMin: 60,
                allowReschedule: true,
                description: 'Schedule your final graduation meeting',
            } satisfies MeetingSchema,
        },
    },
};